version: '3.1'

services:
  db:
    image: mysql:latest
    volumes:
      - ./sqlfiles/:/docker-entrypoint-initdb.d
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=ynov_ci

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

    
