version: '3'

services:
  frontend:
    build:
      context: ./react-form
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: https://votre-api-vercel.vercel.app
    volumes:
      - ./react-form:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
    command: npm start


    
