name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Fix permissions
        run: |
          sudo chown -R $USER:$USER /home/runner/work/ci_cd_react_form/ci_cd_react_form/react-form
          sudo chmod -R 777 /home/runner/work/ci_cd_react_form/ci_cd_react_form/react-form

      - name: Install dependencies
        run: |
          cd react-form
          sudo npm ci --unsafe-perm=true --allow-root
        env:
          NODE_OPTIONS: --max_old_space_size=4096

      - name: Run tests
        run: |
          cd react-form
          npm test
        env:
          CI: true
