name: E2E Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build the stack
        run: docker compose up -d

      - name: Install dependencies
        working-directory: react-form
        run: npm ci

      - name: Run Cypress tests
        working-directory: react-form
        run: |
          npm run build
          npm run cypress:run

      - name: Stop the stack
        if: always()
        run: docker compose down
