name: E2E Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"

      - name: Debug Node.js and npm
        run: |
          node --version
          npm --version
          pwd
          ls -la
          ls -la react-form

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build the stack
        run: docker compose up -d

      - name: Install dependencies
        run: |
          cd react-form
          rm -rf node_modules package-lock.json
          npm cache clean --force
          npm install --no-package-lock

      - name: Run Cypress tests
        run: |
          cd react-form
          npm run build
          npx cypress run

      - name: Stop the stack
        if: always()
        run: docker compose down
